image: docker:latest

variables:
  REGISTRY: $CI_REGISTRY
  PROJECT_PATH: none
  DOCKER_DRIVER: overlay2
  # SELECT ONE OF INTERNAL,EXTERNAL
  CI_DEPLOY_NETWORK: INTERNAL
  CI_DEPLOY_TAG: none
  # SELECT ONE OF public,private
  CI_PUBLISH: public
  # hotfix for https://gitlab.com/gitlab-org/gitlab-ce/issues/64959
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test


build:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  services:
    - name: docker:dind
      command: ["--experimental"]
  stage: build
  script:
    - apk update && apk add git
    - git describe --always --long --dirty > hash.file
    - PROJECT_PATH=$(echo $CI_PROJECT_PATH | tr '[:upper:]' '[:lower:]')
    - CONTAINER_IMAGE=$REGISTRY/$PROJECT_PATH
    - docker pull $CONTAINER_IMAGE:latest || true
    #- gunzip base_image.tar.gz
    #- tar -xvf base_image.tar
    #- sleep 5
    #- docker load < base_image.tar
    - DOCKER_BUILDKIT=0 docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA .
    #- docker build  --pull=false --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA .
    # - rm base_image.tar


    # - docker build --squash --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:latest .
    # - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA .
      #    - docker build --squash --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:git_$CI_COMMIT_SHORT_SHA .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CONTAINER_IMAGE:latest
  tags:
    - docker


.test:
  stage: test
  before_script:
    - apk update && apk add make zip python3
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - PROJECT_PATH=$(echo $CI_PROJECT_PATH | tr '[:upper:]' '[:lower:]')
    - CONTAINER_IMAGE=$REGISTRY/$PROJECT_PATH:$CI_COMMIT_SHORT_SHA
  services:
    - name: docker:19.03.0-dind
      command: ["--experimental"]
  script:
    - echo $CONTAINER_IMAGE
    - unzip data/example/evidence.zip -d data/example/
    - make IMAGE=$CONTAINER_IMAGE DATA=$(pwd)/data/example/ all
  tags:
    - docker
  artifacts:
    paths:
      - data/example/results.zip
    expire_in: 1 week


.pytest:
  stage: test
  image: python:3.8.12
  before_script:
    ## Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H gitlab.lrz.de >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - pip install -U pip poetry pytest
    - poetry config virtualenvs.create false
    - poetry install
  script:
    - echo $CONTAINER_IMAGE
    - python3 -m pytest --cov=bin --cov-report term --junitxml=report.xml
    - coverage xml
  tags:
    - docker
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

